### ISSUE TITLE
No code here?

### ISSUE THREAD

**Issue by Zaijo** [JoePlant/graphviz-excel#1]
Hello, I found this project when exploring capabilities of kumu.io and it's (in)ability to load graphviz format. Do you have any code ready?

**Comment by JoePlant** [comment]
Sorry.... this project didn't quite get to the place I wanted it to.  This project was meant to be more about how can I generate Graphviz files using Excel.

I have done some other work in Graphviz here using the dotml intermediate format and generate .gv files.
https://github.com/JoePlant/dotml

Examples are 
https://github.com/JoePlant/graphviz-scores
https://github.com/JoePlant/xml-architecture
